# subjects =("Python","C++", "JavaScript")
# print(subjects)
# print(len(subjects))
# print(subjects[-1])
# print(subjects[1])
# print(subjects[0:2])
# print("Python" in subjects)
# print("Java" in subjects)
# subject1, subject2,subject3 = subjects
# print(subject1)
# print(subject2)
# print(subject3)
